### ISSUE TITLE
[GameRoles] Add "Opt-in" Support

### ISSUE THREAD

**Issue by LGACode** [Flame442/FlameCogs#36]
**Describe the feature**
*Description of what you would like added*

Please add a simple opt-in mechanism to GameRoles such as a setting where game roles are only given to people who have a specific role. This will allow them to opt into/out of that role (and by extension, this feature) via other methods such as selfrole or react role. This is important for GDPR compliance, the rest of GDPR compliance can be solved on the administrator's end if this option is available.

**Comment by Flame442** [comment]
You might be able to achieve something like this using Sinbad's role management and exclusive roles.
How is not opting in to receiving a role a breach of GDPR?

**Comment by LGACode** [comment]
Ahh exclusive roles would probably work, all though this command would be a bit less pain in the ass haha.

I am not a lawyer, I don't know the specifics of GDPR I just said it because it's the most recognizable. I fear something like that being required in the California Consumer Privacy Act, the Colorado Protections for Consumer Data Privacy (where we operate), or any future privacy protection law.

**Comment by Flame442** [comment]
I just want to also point out that gameroles only uses information that users are publicly displaying. Users have the option to disable game activity (which in turn prevents gameroles from doing anything).
