### ISSUE TITLE
A command that lists all available stocks

### ISSUE THREAD

**Issue by Merp-Me** [Flame442/FlameCogs#49]
**Describe the feature**
By using [p]stocks live or a command like that.
*Description of what you would like added*
This command would list all the available stocks that can be purchased. At the moment, I have not seen any command for it.

**Comment by Flame442** [comment]
Most real-world stocks will work, based on their tickers. An example list of stocks can be found [here](http://eoddata.com/symbols.aspx), although I cannot guarantee this list has every stock available and that every stock on this list is available.
