### ISSUE TITLE
[Monopoly] Few improvement ideas 

### ISSUE THREAD

**Issue by deXxterlab97** [Flame442/FlameCogs#55]
**Describe the feature**
1. When you're buying houses, showing how much money you have prior typing (y/n) would be helpful to know. 
`Are you sure you want to buy 3 houses? (y/n) It will cost $300 at $100 per house.`

2. For those who are not familiar with the US board layout, having the color of the property alongside their name would help a bit. 
(hard to know which one is *St. Charles Place* for example although they're sorted in order)
example:
```
id isM price group name
 0   +    30 brown Baltic Avenue 
 4       100 red   New York Avenue
```

3. Show how much you have at the start of each round, useful when someone paid to you and you want to keep track of it so you know what to do with your money. 
example:
`@deXxterlab97's turn! You have $101.`

**Comment by Flame442** [comment]
Added these suggestions in c41848b. They are in dev right now, and they will be included with the next release.
