### ISSUE TITLE
[Monopoly] Discord Buttons

### ISSUE THREAD

**Issue by turret001** [Flame442/FlameCogs#69]
**Please consider switching to Discord buttons or some sort of equivalent of it.**
*Playing monopoly on the current version is really hard to catch up with. New messages are being sent whenever a user does a move (building houses, rolling, etc.) I think it would be neater to have just 1 message with buttons attached to it and update that message when image needs updating.*

**Comment by Flame442** [comment]
There are active plans for my cogs to utilize the newest discord features (buttons, select menus, etc). These features will not be available for cogs to use until 3.5, so the earliest ETA I have is whenever that comes out.

**Comment by turret001** [comment]
I see, thank you for your quick reply!
