### ISSUE TITLE
[Deepfry] Automatic deepfry/nuke not working.

### ISSUE THREAD

**Issue by TheWizardofGauze** [Flame442/FlameCogs#75]
**Describe the bug**
For a while now I've been unable to get the automatic frychance/nukechance to work. It used to work just fine for me but it stopped working one day. Manual deepfry/nuke still works just fine.

**To Reproduce**
Set frychance/nukechance to 1.
Upload an image.
Image does not get deepfried/nuked automatically.

**Error code**
No traceback.

**Additional information**
Bot has administrator permissions and all intents.

**Comment by Flame442** [comment]
Thank you for reporting this issue. This is due to discord adding authentication flags automatically to image URLs from their CDN, which broke how the autofry logic detected if the attachment was an image.

Resolved in ffb668a. You can run `[p]cog update` to apply the fix on your bot.
